name: Pull Request Template

on:
  pull_request:
    types: [opened]

jobs:
  checkUser:
    runs-on: ubuntu-latest

    steps:
    - name: Check User
      id: check_user
      run: echo "::set-output name=user::${{ github.event.sender.login }}"

    - name: Apply Template
      if: steps.check_user.outputs.user == 'raakesh-m-ctct'
      run: |
        echo "## Description" > pull_request_template.md
        echo "<!-- Describe the changes introduced by this pull request -->" >> pull_request_template.md
        echo "## Checklist" >> pull_request_template.md
        echo "- [ ] Code follows the project's coding standards" >> pull_request_template.md
        echo "- [ ] Changes have been tested" >> pull_request_template.md
        echo "- [ ] Documentation has been updated" >> pull_request_template.md
